version: "2.3"
services:
  node:
    image: flyxdocker/snake-game
    container_name: snake
    user: "node"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - ./:/app
    ports:
      - "80:3000"
  command: node app.js
